FROM nginx
ARG NGINX_EXPOSED_ON
SHELL ["/bin/bash", "-c"]
COPY ./nginx_dev.conf /etc/nginx/nginx.conf
RUN mkdir /etc/nginx/keys
COPY ./certs/nginx_certs/server.crt /etc/nginx/keys/
COPY ./certs/nginx_certs/server.key /etc/nginx/keys/
RUN chmod -R 644 /etc/nginx/keys
ADD ./dist /www/
RUN chown -R www-data:www-data /www
RUN sed -i -e "s/{NGINX_EXPOSED_ON}/$NGINX_EXPOSED_ON/g"  /etc/nginx/nginx.conf
RUN printf "Sitemap: http://localhost:8000/sitemap.xml\n" >> /www/robots.txt